
DROP TABLE BUS_INFO;    

CREATE TABLE BUS_INFO (
    BUS_ID VARCHAR2(100) PRIMARY KEY,
    TOTAL_SEATS NUMBER DEFAULT 50,
    AVAILABLE_SEATS NUMBER,
    PER_KM_COST NUMBER DEFAULT 5
);
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B1');
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B2');




