
DROP TABLE CURRENT_TRAVEL;


CREATE TABLE CURRENT_TRAVEL (
    TRAVEL_ID VARCHAR2(400) PRIMARY KEY,
    USER_ID VARCHAR2(100) REFERENCES USER_PROFILE(USER_ID),
    PICK_POINT VARCHAR2(4000) NOT NULL,
    DROP_POINT VARCHAR2(4000),
    PER_KM_COST NUMBER(5, 2) DEFAULT 5,
    TOTAL_COST NUMBER(10, 2),
    current_longitude NUMBER,
    current_latitude NUMBER,
    dropoff_longitude NUMBER,
    dropoff_latitude NUMBER

);


