
DROP TABLE CURRENT_TRAVEL;


CREATE TABLE CURRENT_TRAVEL (
    TRAVEL_ID VARCHAR2(400) PRIMARY KEY,
    USER_ID VARCHAR2(100) REFERENCES USER_PROFILE(USER_ID),

    PICK_POINT VARCHAR2(4000) NOT NULL,
    DROP_POINT VARCHAR2(4000),
    PER_KM_COST NUMBER DEFAULT 5,
    TOTAL_COST NUMBER,
    current_longitude VARCHAR2(4000),
    current_latitude VARCHAR2(4000),
    dropoff_longitude VARCHAR2(4000),
    dropoff_latitude VARCHAR2(4000),
    TRAVEL_DATE DATE DEFAULT SYSDATE,
    TRAVEL_STATUS VARCHAR2(20) DEFAULT 'ONGOING'

);


