
DROP TABLE CURRENT_TRAVEL;


CREATE TABLE CURRENT_TRAVEL (
    TRAVEL_ID VARCHAR2(100) PRIMARY KEY,
    USER_ID VARCHAR2(100) REFERENCES USER_PROFILE(USER_ID),
    PICK_POINT VARCHAR2(100) NOT NULL,
    DROP_POINT VARCHAR2(100),
    PER_KM_COST NUMBER(5, 2),
    TOTAL_COST NUMBER(10, 2)
);