


DROP TABLE RECHARGE_HISTORY;

CREATE TABLE RECHARGE_HISTORY (
    RECHARGE_ID VARCHAR2(100) PRIMARY KEY,
    USER_ID VARCHAR2(100) REFERENCES USER_PROFILE(USER_ID),
    RECHARGE_DATE TIMESTAMP,
    RECHARGE_AMOUNT NUMBER(10, 2),
    PAYMENT_METHOD VARCHAR2(50)
);

