-- TRAVEL_HISTORY table for PostgreSQL/Supabase
DROP TABLE IF EXISTS TRAVEL_HISTORY CASCADE;

CREATE TABLE TRAVEL_HISTORY (
    HISTORY_ID VARCHAR(400) PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    USER_ID VARCHAR(400) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    TRAVEL_DATE DATE DEFAULT CURRENT_DATE,
    TRAVEL_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PICK_POINT TEXT,
    DROP_POINT TEXT,
    TOTAL_COST DECIMAL(10, 2),
    REMAINING_BALANCE DECIMAL(10, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_travel_history_user_id ON TRAVEL_HISTORY(USER_ID);
CREATE INDEX idx_travel_history_travel_date ON TRAVEL_HISTORY(TRAVEL_DATE);
CREATE INDEX idx_travel_history_travel_time ON TRAVEL_HISTORY(TRAVEL_TIME);
