-- CURRENT_TRAVEL table for PostgreSQL/Supabase
DROP TABLE IF EXISTS CURRENT_TRAVEL CASCADE;

CREATE TABLE CURRENT_TRAVEL (
    TRAVEL_ID VARCHAR(400) PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    USER_ID VARCHAR(100) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    PICK_POINT TEXT NOT NULL,
    DROP_POINT TEXT,
    PER_KM_COST DECIMAL(10, 2) DEFAULT 5.00,
    TOTAL_COST DECIMAL(10, 2),
    CURRENT_LONGITUDE VARCHAR(100),
    CURRENT_LATITUDE VARCHAR(100),
    DROPOFF_LONGITUDE VARCHAR(100),
    DROPOFF_LATITUDE VARCHAR(100),
    TRAVEL_DATE DATE DEFAULT CURRENT_DATE,
    TRAVEL_STATUS VARCHAR(20) DEFAULT 'ONGOING' CHECK (TRAVEL_STATUS IN ('ONGOING', 'COMPLETED', 'CANCELLED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger to update updated_at on CURRENT_TRAVEL
CREATE TRIGGER update_current_travel_updated_at 
    BEFORE UPDATE ON CURRENT_TRAVEL
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Create index for better performance
CREATE INDEX idx_current_travel_user_id ON CURRENT_TRAVEL(USER_ID);
CREATE INDEX idx_current_travel_status ON CURRENT_TRAVEL(TRAVEL_STATUS);
