-- RECHARGE_HISTORY table for PostgreSQL/Supabase
DROP TABLE IF EXISTS RECHARGE_HISTORY CASCADE;

CREATE TABLE RECHARGE_HISTORY (
    RECHARGE_ID VARCHAR(100) PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    USER_ID VARCHAR(100) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    RECHARGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RECHARGE_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50) CHECK (PAYMENT_METHOD IN ('CARD', 'BKASH', 'NAGAD', 'ROCKET', 'UPAY')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_recharge_history_user_id ON RECHARGE_HISTORY(USER_ID);
CREATE INDEX idx_recharge_history_date ON RECHARGE_HISTORY(RECHARGE_DATE);
CREATE INDEX idx_recharge_history_payment_method ON RECHARGE_HISTORY(PAYMENT_METHOD);
