-- BUS_INFO table for PostgreSQL/Supabase
DROP TABLE IF EXISTS BUS_INFO CASCADE;

CREATE TABLE BUS_INFO (
    BUS_ID VARCHAR(100) PRIMARY KEY,
    TOTAL_SEATS INTEGER DEFAULT 50,
    AVAILABLE_SEATS INTEGER DEFAULT 50,
    PER_KM_COST DECIMAL(10, 2) DEFAULT 5.00,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger to update updated_at on BUS_INFO
CREATE TRIGGER update_bus_info_updated_at 
    BEFORE UPDATE ON BUS_INFO
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Insert sample bus data
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B1');
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B2');
