-- Complete Supabase Database Setup for Smart Transit Application
-- IMPORTANT: This must be executed in Supabase Dashboard > SQL Editor

-- STEP 1: Enable UUID extension in Supabase Dashboard
-- Go to Database > Extensions > Search for "uuid-ossp" > Enable it
-- OR run this command in Supabase SQL Editor:
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- STEP 2: After enabling the extension, run the rest of this script

-- Drop existing tables and sequences if they exist (in reverse dependency order)
DROP TABLE IF EXISTS CURRENT_TRAVEL CASCADE;
DROP TABLE IF EXISTS TRAVEL_HISTORY CASCADE;
DROP TABLE IF EXISTS RECHARGE_HISTORY CASCADE;
DROP TABLE IF EXISTS BUS_INFO CASCADE;
DROP TABLE IF EXISTS USER_PROFILE CASCADE;
DROP SEQUENCE IF EXISTS user_id_seq CASCADE;

-- Create sequence for user_id generation
CREATE SEQUENCE user_id_seq START 1;

-- 1. USER_PROFILE table
CREATE TABLE USER_PROFILE (
    USER_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    CARD_ID VARCHAR(50) UNIQUE NOT NULL,
    BALANCE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    DOB TIMESTAMP NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    AGE INTEGER,
    ADDRESS VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
);

-- 2. BUS_INFO table
CREATE TABLE BUS_INFO (
    BUS_ID VARCHAR(100) PRIMARY KEY,
    TOTAL_SEATS INTEGER DEFAULT 50,
    AVAILABLE_SEATS INTEGER DEFAULT 50,
    PER_KM_COST DECIMAL(10, 2) DEFAULT 5.00,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
);

-- 3. CURRENT_TRAVEL table
CREATE TABLE CURRENT_TRAVEL (
    TRAVEL_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID VARCHAR(100) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    PICK_POINT TEXT NOT NULL,
    DROP_POINT TEXT,
    PER_KM_COST DECIMAL(10, 2) DEFAULT 5.00,
    TOTAL_COST DECIMAL(10, 2),
    CURRENT_LONGITUDE VARCHAR(100),
    CURRENT_LATITUDE VARCHAR(100),
    DROPOFF_LONGITUDE VARCHAR(100),
    DROPOFF_LATITUDE VARCHAR(100),
    TRAVEL_DATE DATE DEFAULT CURRENT_DATE,
    TRAVEL_STATUS VARCHAR(20) DEFAULT 'ONGOING' CHECK (TRAVEL_STATUS IN ('ONGOING', 'COMPLETED', 'CANCELLED')),
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    UPDATED_AT TIMESTAMP DEFAULT NOW()
);

-- 4. TRAVEL_HISTORY table
CREATE TABLE TRAVEL_HISTORY (
    HISTORY_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID VARCHAR(400) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    TRAVEL_DATE DATE DEFAULT CURRENT_DATE,
    TRAVEL_TIME TIMESTAMP DEFAULT NOW(),
    PICK_POINT TEXT,
    DROP_POINT TEXT,
    TOTAL_COST DECIMAL(10, 2),
    REMAINING_BALANCE DECIMAL(10, 2),
    CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- 5. RECHARGE_HISTORY table
CREATE TABLE RECHARGE_HISTORY (
    RECHARGE_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID VARCHAR(100) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    RECHARGE_DATE TIMESTAMP DEFAULT NOW(),
    RECHARGE_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50) CHECK (PAYMENT_METHOD IN ('CARD', 'BKASH', 'NAGAD', 'ROCKET', 'UPAY', 'STRIPE')),
    TRANSACTION_ID VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'completed' CHECK (STATUS IN ('completed', 'pending', 'failed')),
    CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_current_travel_user_id ON CURRENT_TRAVEL(USER_ID);
CREATE INDEX idx_current_travel_status ON CURRENT_TRAVEL(TRAVEL_STATUS);
CREATE INDEX idx_travel_history_user_id ON TRAVEL_HISTORY(USER_ID);
CREATE INDEX idx_travel_history_travel_date ON TRAVEL_HISTORY(TRAVEL_DATE);
CREATE INDEX idx_travel_history_travel_time ON TRAVEL_HISTORY(TRAVEL_TIME);
CREATE INDEX idx_recharge_history_user_id ON RECHARGE_HISTORY(USER_ID);
CREATE INDEX idx_recharge_history_date ON RECHARGE_HISTORY(RECHARGE_DATE);
CREATE INDEX idx_recharge_history_payment_method ON RECHARGE_HISTORY(PAYMENT_METHOD);

-- Insert sample data
-- Admin users (with USER_ID starting with 'A' for admin identification)
INSERT INTO USER_PROFILE (USER_ID, NAME, EMAIL, PHONE, CARD_ID, BALANCE, DOB, ADDRESS, PASSWORD)
VALUES 
    ('A000001', 'Super Admin', 'admin@smarttransit.com', '+1234567890', 'ADMIN001', 10000, '1990-01-01 00:00:00', 'Admin Office, Smart Transit HQ', 'admin123'),
    ('A000002', 'John Doe Admin', 'john.doe@example.com', '+123456789', 'ADMIN002', 5000, '1996-04-12 10:00:00', '123 Street, City, Country', 'password123');

-- Regular users
INSERT INTO USER_PROFILE (NAME, EMAIL, PHONE, CARD_ID, BALANCE, DOB, ADDRESS, PASSWORD)
VALUES 
    ('Jane Smith', 'jane.smith@example.com', '+987654321', '520028B840', 1000, '1992-05-15 09:30:00', '456 Avenue, Town, Country', 'password123'),
    ('Mike Johnson', 'mike.johnson@example.com', '+1122334450', '520026D872', 750, '1998-02-22 08:15:00', '789 Boulevard, City, Country', 'password123'),
    ('Chris Johnson', 'chris.johnson@example.com', '+1122334460', '520028E289', 750, '1995-01-10 08:30:00', '789 Boulevard, City, Country', 'password123'),
    ('Alex Johnson', 'alex.johnson@example.com', '+1122334470', '4400309616', 750, '1997-03-05 10:15:00', '789 Boulevard, City, Country', 'password123');

-- Sample bus data
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B1');
INSERT INTO BUS_INFO (BUS_ID) VALUES ('B2');

-- Note: You may need to update a specific user's balance after creation
-- Example: UPDATE USER_PROFILE SET BALANCE = 30 WHERE USER_ID = 'U000001';
