

DROP TABLE TRAVEL_HISTORY;


CREATE TABLE TRAVEL_HISTORY (
    HISTORY_ID VARCHAR2(400) PRIMARY KEY,
    USER_ID VARCHAR2(400) REFERENCES USER_PROFILE(USER_ID),
    TRAVEL_DATE DATE,
    TRAVEL_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    PICK_POINT VARCHAR2(4000),
    DROP_POINT VARCHAR2(4000),
    TOTAL_COST NUMBER,
    REMAINING_BALANCE NUMBER
);
