

DROP TABLE TRAVEL_HISTORY;


CREATE TABLE TRAVEL_HISTORY (
    HISTORY_ID VARCHAR2(100) PRIMARY KEY,
    USER_ID VARCHAR2(100) REFERENCES USER_PROFILE(USER_ID),
    TRAVEL_DATE DATE,
    TRAVEL_TIME VARCHAR2(20),
    PICK_POINT VARCHAR2(100),
    DROP_POINT VARCHAR2(100),
    TOTAL_COST NUMBER(10, 2),
    REMAINING_BALANCE NUMBER(10, 2)
);
