CREATE TABLE USER_PROFILE (
    USER_ID VARCHAR2(100) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(20),
    CARD_ID VARCHAR2(20) UNIQUE,
    BALANCE NUMBER(10, 2),
    AGE NUMBER(3),
    ADDRESS VARCHAR2(255)
);
